### ISSUE TITLE
Gysahl Greens Crashing on Harvest

### ISSUE THREAD

**Issue by jordan-moore** [Xalcon/ChocoCraft3#26]
I've been seeing this error crop up in a couple of packs and thought I'd raise it.

As a standalone mod I don't think ChocoCraft3 has this issue but with any mod that adds right click harvesting (Pam's Harvestcraft, Gentle Harvest, Simple Harvest) or a few automated harvesters machines.

I've reached out to a few of the harvest mod devs but it seems unfixable on their end. 

```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=chococraft:gysahl_green, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
	at com.workshopcraft.SimpleHarvest.CropHandler.onPlayerUse(CropHandler.java:100) ~[CropHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2006_CropHandler_onPlayerUse_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1101) ~[ForgeHooks.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398) ~[bsa.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by jordan-moore** [comment]
Issue was stemming from a duplicate harvest mod simple harvest. After disabling no issues with harvesting from gentle harvest or pam's harvestcraft
